# Список шаблонов файлов, которые следует исключить из форматирования и проверки.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "dist",
    "node_modules",
    "venv",
    "Pipfile",
    "Pipfile.lock",
    ]

# По умолчанию при запуске ruff включается функция исправления ошибок
# (переопределяется флагами командной строки --fix и --no-fix).
# Включает только автоматические исправления, если не указан --unsafe-fixes.
fix = true

# Список шаблонов файлов для включения в линтинг.
include = [
    "*.py",
    "*.toml",
    "*.rs",
    ]

# Количество пробелов на уровень отступа (табуляции).
indent-width = 4

#Длина строки, которую следует использовать при нарушении правила длинных строк (например, E501)
# и при которой isort и средство форматирования предпочитают переносить строки.
line-length = 120

# Стиль форматирования сообщений о нарушениях:
# "full" (по умолчанию) (отображает исходный код),
# "concise", "grouped" (группировка сообщений по файлам),
# "json" (машиночитаемый),
# "junit" (машиночитаемый XML),
# "github" (аннотации GitHub Actions),
# "gitlab" (отчет о качестве кода в GitLab CI),
# "pylint" (текстовый формат Pylint)
# "azure" (команды ведения журнала в Azure Pipeline).
# output-format = "grouped"

# Следует ли автоматически исключать файлы, которые игнорируются .ignore, .gitignore, .git/info/exclude,
# а также глобальными gitignore файлами. Включено по умолчанию.
respect-gitignore = true

# Показывать ли перечисление всех исправленных нарушений lint (переопределяется --show-fixes флагом командной строки).
# show-fixes = true

# Каталоги, которые следует учитывать при выборе между импортом из первой и третьей стороны.
src = [
    ".",
    "src",
    "test",
    ]

# Минимальная версия Python, на которую нужно ориентироваться, например,
# при рассмотрении возможности автоматического обновления кода, такого как переписывание аннотаций типов.
# Ruff не будет предлагать изменения, использующие функции, недоступные в указанной версии.
# Тип: "py37" | "py38" | "py39" | "py310" | "py311" | "py312" | "py313" | "py314"
target-version = "py313"


# Настраивает способ форматирования кода в Ruff.
[format]

# Форматировать ли фрагменты кода в строках документации.
docstring-code-format = true

# Задайте длину строки, используемую при форматировании фрагментов кода в документации.
docstring-code-line-length = "dynamic"

# Использовать ли пробелы или табуляцию для отступов.
# Тип: "space" | "tab"
indent-style = "space"

# Настраивает предпочтительный символ кавычек для строк. Рекомендуемые варианты:
#   * double (по умолчанию): Используйте двойные кавычки "
#   * single: Используйте одинарные кавычки '
# Тип: "double" | "single" | "preserve"
quote-style = "single"

# Ruff использует существующие конечные запятые в качестве указания на то,
# что короткие строки следует оставлять отдельными.
# Если для этого параметра установлено значение true, волшебная конечная запятая игнорируется.
skip-magic-trailing-comma = false


# Настраивает проверку кода в Ruff.
[lint]

# Список кодов правил или префиксов, которые нужно игнорировать.
# Префиксы могут указывать на конкретные правила (например, F841), целые категории (например, F) или что-то среднее.
# Skip unused variable rules (`F841`).
# ignore = ["F841"]

# Список кодов правил или префиксов для включения.
# Префиксы могут указывать на конкретные правила (например, F841), целые категории (например, F) или что-то среднее.
# Значение по умолчанию: ["E4", "E7", "E9", "F"]
# On top of the defaults (`E4`, E7`, `E9`, and `F`), enable flake8-bugbear (`B`) and flake8-quotes (`Q`).
select = ["E4", "E7", "E9", "F", "B", "Q"]


# Параметры плагина flake8-quotes
[lint.flake8-quotes]

# Стиль цитирования, который следует использовать для строк документации (одинарный или двойной).
# Тип: "single" | "double"
docstring-quotes = "single"

# Какой стиль цитирования предпочтительнее для встроенных строк (одинарный или двойной)?.
# При использовании средства форматирования убедитесь, что для format.quote-style задан тот же предпочтительный стиль цитирования.
# Значение по умолчанию: "double"
# Тип: "single" | "double"
inline-quotes = "single"


# Параметры для плагина isort.
[lint.isort]

# Сортировка импорта с учётом регистра.
# Обратите внимание, что при включении параметр order-by-type будет иметь приоритет над этим параметром.
# Значение по умолчанию: false
case-sensitive = true

# Не сортируйте прямой импорт (например, import sys) перед импортом из модуля (например, from itertools import groupby). Вместо этого сортируйте импорт по модулю, независимо от стиля импорта.
# Значение по умолчанию: false
force-sort-within-sections = false

# Следует ли при сортировке помещать import from-импорты перед обычными импортами.
# Значение по умолчанию: false
from-first = false

# Количество пустых строк, которые нужно оставить после импорта. Используйте -1 для автоматического определения.
# Ruff оставляет не более одной пустой строки после импорта в файлах-заготовках (файлах с расширением .pyi)
# в соответствии с рекомендациями по стилю набора текста (источник).
# При использовании средства форматирования совместимы только значения -1, 1, и 2,
# поскольку оно требует наличия как минимум одной пустой и не более чем двух пустых строк после импорта.
# Значение по умолчанию: -1
lines-after-imports = 2

# Количество строк, которые нужно разместить между «прямым» и import from импортом.
# При использовании средства форматирования совместимы только значения 0 и 1,
# поскольку оно сохраняет до одной пустой строки после импорта во вложенных блоках.
# Значение по умолчанию: 0
lines-between-types = 1


# Параметры плагина mccabe .
[lint.mccabe]

# Максимальная сложность по Маккейбу, при превышении которой возникают ошибки C901 .
# Значение по умолчанию: 10
max-complexity = 15


# Параметры для плагина pylint.
[lint.pylint]

# Максимальное количество аргументов, допустимое для определения функции или метода (см. PLR0913).
# Значение по умолчанию: 5
# max-args = 10

# Максимальное количество логических выражений, допустимых в одном операторе if (см. PLR0916).
# Значение по умолчанию: 5
# max-bool-expr = 10

# Максимальное количество ветвей, допустимое для тела функции или метода (см. PLR0912).
# Значение по умолчанию: 12
# max-branches = 15

# Максимальное количество локальных переменных, допустимое для тела функции или метода (см. PLR0914).
# Значение по умолчанию: 15
# max-locals = 20

# Максимальное количество вложенных блоков, допустимое в теле функции или метода (см. PLR1702).
# Значение по умолчанию: 5
# max-nested-blocks = 10

# Максимальное количество общедоступных методов, разрешённых для класса (см. PLR0904).
# Значение по умолчанию: 20
# max-public-methods = 30

# Максимальное количество операторов в теле функции или метода (см. PLR0915).
# Значение по умолчанию: 50
# max-statements = 75
